// Generated by CoffeeScript 1.4.0

/*
	FlexNav.js 0.4.5

	Copyright 2013, Jason Weaver http://jasonweaver.name
	Released under the WTFPL license
	http://sam.zoy.org/wtfpl/

//
*/


(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $.fn.flexNav = function(options) {
    var $nav, is_touch_device, resizer, settings;
    settings = $.extend({
      'breakpoint': '800',
      'animationSpeed': 'fast'
    }, options, $nav = $(this), resizer = function() {
      if ($(window).width() <= settings.breakpoint) {
        $nav.removeClass("lg-screen").addClass("sm-screen");
        $nav.hide();
        return $('.item-with-ul').off();
      } else {
        $nav.removeClass("sm-screen").addClass("lg-screen");
        $nav.fadeIn();
        return $('.item-with-ul').on({
          mouseenter: function() {
            return $(this).find('>ul').slideDown(settings.animationSpeed);
          },
          mouseleave: function() {
            return $(this).find('>ul').slideUp(settings.animationSpeed);
          }
        });
      }
    }, is_touch_device = function() {
      return !!(__indexOf.call(window, 'ontouchstart') >= 0);
    }, is_touch_device() ? $nav.addClass('flexNav-touch') : $nav.addClass('flexNav-no-touch'), $(this).find("li").each(function() {
      if ($(this).has("ul").length) {
        return $(this).addClass("item-with-ul");
      }
    }), $('.menu-button').on('click', function() {
      return $nav.slideToggle(settings.animationSpeed);
    }), $('.menu-button, .item-with-ul').append('<span class="touch-button"><i class="navicon">&#9660;</i></span>'), $('.touch-button').on('click', function() {
      return $(this).parent('.item-with-ul').find('>ul').slideToggle(settings.animationSpeed);
    }), $('.item-with-ul *').focus(function() {
      $(this).parent('.item-with-ul').parent().find(".open").not(this).removeClass("open");
      return $(this).parent('.item-with-ul').find('>ul').addClass("open");
    }));
    resizer();
    return $(window).on('resize', resizer);
  };

}).call(this);
